### ISSUE TITLE
Signup flow error in pro buyer program

### ISSUE THREAD

**Issue by joauea** [artsy/microgravity#11]
Trying to create an account from the [mobile professional buyer page in staging](https://m-staging.artsy.net/professional-buyer) throws the following error:

![screen shot 2016-09-06 at 6 16 36 pm](https://cloud.githubusercontent.com/assets/15615381/18293068/9d742ebe-745e-11e6-9262-254e5806a0a8.png)

A second attempt throws the following:

![screen shot 2016-09-06 at 6 17 00 pm](https://cloud.githubusercontent.com/assets/15615381/18293078/aecd118a-745e-11e6-9f72-78abb1a82f9b.png)

Can someone take a look at potential causes of this, and confirm whether these accounts are actually being created?

**Comment by joauea** [comment]
@anipetrov

**Comment by alloy** [comment]
This is done by https://github.com/artsy/force/pull/140
