### ISSUE TITLE
QA on article-related events

### ISSUE THREAD

**Issue by joauea** [artsy/microgravity#21]
Following up on https://github.com/artsy/force-private/issues/5375.

cc: @kanaabe @owendodd @anipetrov

1) `Article share [related article]` doesn't fire from related articles (under "What to read next").

![image 2016-09-13 at 1 14 18 pm](https://cloud.githubusercontent.com/assets/15615381/18483865/015d62d8-79b4-11e6-97d2-b5745e944e07.png)

---

Additional notes for superarticles:

1) `Article impression [table of contents]` doesn't fire for either top or bottom TOC.

![image 2016-09-13 at 1 17 20 pm](https://cloud.githubusercontent.com/assets/15615381/18483959/6c8fa070-79b4-11e6-95df-1dee7793ce87.png)

![image 2016-09-13 at 1 17 58 pm](https://cloud.githubusercontent.com/assets/15615381/18483974/82639fd2-79b4-11e6-96e3-3dd5ff364c24.png)

**Comment by kanaabe** [comment]
also TODO: Follow button image set

**Comment by eessex** [comment]
@joelauerbach - I set up impressions for the related box, but didn't include the URL's because there are 10 and it is a very long list -- let me know if this seems practical or you'd like to get the slugs.

**Comment by eessex** [comment]
@kanaabe - looks like the follow button clicks are already being tracked. Tried to add impressions as well, but the current setup is dependent on scrolling (not possible inside an imageset). Do you think click-tracking is sufficient for this case?

**Comment by joauea** [comment]
@eessex Thanks! I think we'd like to at least get the Positron IDs of the related articles, if possible.
