### ISSUE TITLE
Mobile Email Signup Modal

### ISSUE THREAD

**Issue by owendodd** [artsy/microgravity#28]
This modal should display for users that have viewed 4 articles in the past 30 days. Closing the modal should hide it for the user for 30 days. T

It would be great if we could auto-populate the form for signed in / not signed up users. 

The form should not display for email traffic. 

For these we should be tracking: impressions, signups, and closes.

🌟 

![screen shot 2016-09-19 at 1 35 57 pm](https://cloud.githubusercontent.com/assets/3196536/18642286/19259e58-7e6e-11e6-9425-d0766bc12888.png)

Sketch File: https://cl.ly/37263Y2P0l2x

**Comment by owendodd** [comment]
Would be good to test this on iOS too before we roll it out. Not sure how it will feel there, could be a lil funky. 

@kanaabe would we hypothetically be able to block it from showing in app if it does feel weird?

**Comment by kanaabe** [comment]
I think we're [removing trials](https://github.com/artsy/eigen/pull/1831) on Eigen which means users can only browse articles on iOS if they're signed up for Artsy already. We can show it for users who aren't signed up for the Daily Editorial email, or omit signups from iOS entirely.

**Comment by alloy** [comment]
> I think we're removing trials on Eigen

@kanaabe Correct 👍

**Comment by kanaabe** [comment]
cc @owendodd ^ up to you!
