### ISSUE TITLE
Artists page see more button unstyled

### ISSUE THREAD

**Issue by kanaabe** [artsy/microgravity#34]
The "See More" button on the bottom of the artists page is unstyled and should look like the other avant garde buttons

![img_0261](https://cloud.githubusercontent.com/assets/2236794/18821739/f82921bc-8376-11e6-9d0a-e1e36078bb71.PNG)

**Comment by kanaabe** [comment]
The main artist page is also missing some padding on the header. 

![img_0262](https://cloud.githubusercontent.com/assets/2236794/18821777/5b0ee0f0-8377-11e6-8ffc-5770795110c5.PNG)

**Comment by eessex** [comment]
@kanaabe - got the button styled, but the title spacing only seems to occur in the app, not in the browser.

**Comment by 1aurabrown** [comment]
It looks like this was closed by https://github.com/artsy/microgravity/pull/41 ? padding problem will be a separate fix, as Craig outlines in eve's pr, and perhaps should be a separate issue.
