### ISSUE TITLE
Partner submitted bios on Artist page

### ISSUE THREAD

**Issue by briansw** [artsy/microgravity#39]
Related to: https://github.com/artsy/admin_metadata/issues/58
#### Priority
- [ ] Artsy bio
- [ ] Approved partner bio

Italicize attribution line:

![screen shot 2016-10-04 at 4 54 38 pm](https://cloud.githubusercontent.com/assets/1022172/19092106/4271c886-8a53-11e6-8f58-2d566cf4b7f0.png)

**Comment by mzikherman** [comment]
This one is going to be tricky.

The other 3, artist/artwork page in Force and then artwork page in Microgravity, are all backed by Metaphysics. The artist page in MG isn't. I don't know if it makes sense to duplicate part of that logic in Microgravity here and get it working, vs rewriting the page to use Metaphysics.

I vote for the latter (rewrite the artist page to use Metaphysics).

**Comment by mzikherman** [comment]
Actually it might be fairly simple to keep it as-is but implement the bio part in Metaphysics. If it's really fast maybe it's worth it, but in general the page should probably be rewritten anyway.

**Comment by briansw** [comment]
There were plans to redo the artist page on microgravity (https://github.com/artsy/microgravity-private/issues/1245), but it was tabled due to other priorities. Ideally, we could come up with a solution to display bios that doesn't require too much effort.

**Comment by mzikherman** [comment]
Ok https://github.com/artsy/microgravity/pull/54 updates the bio page to support the partner bios.

However, what's still not done is being able to render the 'Bio' link vs hiding it altogether (ie- knowing that it should be rendered) if there is no Artsy bio but there is a featured one. That's the one where its tricky because of not using Metaphysics.

**Comment by alloy** [comment]
@briansw @mzikherman Is the agreement here to hold off implementing this in MG for now? /cc @tayapage6

**Comment by mzikherman** [comment]
Actually this was done! https://github.com/artsy/microgravity/pull/54
