### ISSUE TITLE
[Differentiation] Promoted banner for Articles

### ISSUE THREAD

**Issue by owendodd** [artsy/microgravity#6]
Mobile version of https://github.com/artsy/force-private/issues/5254

![iphone 6 copy 4](https://cloud.githubusercontent.com/assets/3196536/18066449/762ff4d6-6e06-11e6-950e-dae494935442.png)

Sketch file: https://www.dropbox.com/s/d4x3may28sdv2jr/DifferentiationMobileSpec.sketch?dl=0

**Comment by eessex** [comment]
@owendodd -- I wanted to check in about the titles for the promoted content bar -- currently titles give the auction house and the name of the sale in many cases but not all.  Two options I've explored are showing the full name, or clipping off anything following a colon, which looks like the example you sent above.

![screen shot 2016-09-12 at 6 25 22 pm](https://cloud.githubusercontent.com/assets/1497424/18477580/24ce48a8-799c-11e6-80a0-1eeb283627e0.png)
![screen shot 2016-09-12 at 6 25 30 pm](https://cloud.githubusercontent.com/assets/1497424/18477581/24d8dea8-799c-11e6-9ddf-50525d6080b3.png)

**Comment by owendodd** [comment]
@eessex I think the full name will work!
