### ISSUE TITLE
Miami Beach Signup

### ISSUE THREAD

**Issue by briansw** [artsy/microgravity#63]
- Force issue: https://github.com/artsy/force/issues/365
- Image: https://cl.ly/3f0u463V3O3w
- Scrolling behavior: https://cl.ly/243s1R051033
- Analytics issue to follow
- Display modal for all logged out users that hit the page from outside Artsy:
  - artsy.net/feature/miami-art-week-2016
  - all miami microsites
  - home (tbd)
- Stop displaying module on Dec 5

#### Preview (Nov 16 - Nov 21)
- Get early access to thousands of artworks at Miami Art Week

#### Live (Nov 22 - Dec 5)
- Get exclusive access to thousands of artworks at Miami Art Week

![mobile-spec](https://cloud.githubusercontent.com/assets/1022172/20309384/bd42951c-ab15-11e6-97e7-dcc7fda5d1a3.jpg)

**Comment by alloy** [comment]
This is done.
