### ISSUE TITLE
Links with ?for_sale=true in the url are trimmed when routed to MG

### ISSUE THREAD

**Issue by briansw** [artsy/microgravity#85]
Example: opening https://www.artsy.net/artist/betty-woodman?for_sale=true on a phone will cut the params.

**Comment by 1aurabrown** [comment]
To clarify, at no point am i seeing the params being stripped, they just aren't being handled, did the artist view on martsy every previously support the for_sale param?

**Comment by xtina-starr** [comment]
@1aurabrown I looked into this as well before getting pulled on to another issue. I saw the same thing and don't think for_sale params were ever supported for this view (at least via the URL). The filters are being handled client-side. I think that's a pretty consistent approach for martsy. The `/collect` view is the same.

**Comment by 1aurabrown** [comment]
@xtina-starr yep, it looked as though there was intended support for the `filter[]` params, which seemed to work, but i don't know anywhere where we use that parameter. it's not present anywhere else in microgravity. since force uses `for_sale` instead, it seemed easiest to consolidate.
