### ISSUE TITLE
[Analytics] Tracking on inquiry questionnaire

### ISSUE THREAD

**Issue by joauea** [artsy/microgravity#99]
If possible, it would be great to replicate the tracking on the inquiry questionnaire flow done in Force (https://github.com/artsy/force/blob/5534989c43722ffa345fb0c9b1dc8a9f357726ee/analytics/inquiry_questionnaire.js). 

The most important piece on our end is the `context` that gets passed to the `created_account` event (https://github.com/artsy/force/blob/5534989c43722ffa345fb0c9b1dc8a9f357726ee/analytics/inquiry_questionnaire.js#L171). Even if we could just get that for now, it would be very helpful.

![image 2017-01-19 at 2 07 15 pm](https://cloud.githubusercontent.com/assets/15615381/22121479/35dbe8ba-de52-11e6-8f5e-d4c1aebf0a9b.png)

**Comment by broskoski** [comment]
Talked about this with @joelauerbach offline... closing this issue as MG proxies Force for inquiries, so its a matter of distinguishing where the inquiry originates from based on cookies.
